<?php
$ConstellationsFilter = [
    'And','Ant', 'Aps', 'Aql', 'Aqr', 'Ara', 'Ari', 'Aur', 'Boo', 'Cae', 'Cam', 'Cap', 'Car', 'Cas', 'Cen', 'Cep', 'Cet', 'Cha', 'Cir', 'CMa', 'CMi', 'Cnc', 'Col', 'Com', 'CrA', 'CrB', 'Crt', 'Cru', 'Crv', 'CVn', 'Cyg', 'Del', 'Dor', 'Dra', 'Equ', 'Eri', 'For', 'Gem', 'Gru', 'Her', 'Hor', 'Hya', 'Hyi', 'Ind', 'Lac', 'Leo', 'Lep', 'Lib', 'LMi', 'Lup', 'Lyn', 'Lyr', 'Men', 'Mic', 'Mon', 'Mus', 'Nor', 'Oct', 'Oph', 'Ori', 'Pav', 'Peg', 'Per', 'Phe', 'Pic', 'PsA', 'Psc', 'Pup', 'Pyx', 'Ret', 'Scl', 'Sco', 'Sct', 'Ser', 'Sex', 'Sge', 'Sgr', 'Tau', 'Tel', 'TrA', 'Tri', 'Tuc', 'UMa', 'UMi', 'Vel', 'Vir', 'Vol', 'Vul',
];

$Constellations_filters_and_names = [
    ['And', 'Andromède'],
    ['Ant', 'Machine Pneumatique'],
    ['Aps', 'Oiseau de Paradis'],
    ['Aql', 'Aigle'],
    ['Aqr', 'Verseau'],
    ['Ara', 'Autel'],
    ['Ari', 'Bélier'],
    ['Aur', 'Cocher'],
    ['Boo', 'Bouvier'],
    ['Cae', 'Burin'],
    ['Cam', 'Girafe'],
    ['Cap', 'Capricorne'],
    ['Car', 'Carène'],
    ['Cas', 'Cassiopée'],
    ['Cen', 'Centaure'],
    ['Cep', 'Céphée'],
    ['Cet', 'Baleine'],
    ['Cha', 'Caméléon'],
    ['Cir', 'Compas'],
    ['CMa', 'Grand Chien'],
    ['CMi', 'Petit Chien'],
    ['Cnc', 'Cancer'],
    ['Col', 'Colombe'],
    ['Com', 'Chevelure de Bérénice'],
    ['CrA', 'Couronne Australe'],
    ['CrB', 'Couronne Boréale'],
    ['Crt', 'Coupe'],
    ['Cru', 'Croix du Sud'],
    ['Crv', 'Corbeau'],
    ['CVn', 'Chiens de Chasse'],
    ['Cyg', 'Cygne'],
    ['Del', 'Dauphin'],
    ['Dor', 'Dorade'],
    ['Dra', 'Dragon'],
    ['Equ', 'Petit Cheval'],
    ['Eri', 'Eridan'],
    ['For', 'Fourneau'],
    ['Gem', 'Gémeaux'],
    ['Gru', 'Grue'],
    ['Her', 'Hercule'],
    ['Hor', 'Horloge'],
    ['Hya', 'Hydre Femelle'],
    ['Hyi', 'Hydre Mâle'],
    ['Ind', 'Indien'],
    ['Lac', 'Lézard'],
    ['Leo', 'Lion'],
    ['Lep', 'Lièvre'],
    ['Lib', 'Balance'],
    ['LMi', 'Petit Lion'],
    ['Lup', 'Loup'],
    ['Lyn', 'Lynx'],
    ['Lyr', 'Lyre'],
    ['Men', 'Table'],
    ['Mic', 'Microscope'],
    ['Mon', 'Licorne'],
    ['Mus', 'Mouche'],
    ['Nor', 'Règle'],
    ['Oct', 'Octant'],
    ['Oph', 'Ophiuchus'],
    ['Ori', 'Orion'],
    ['Pav', 'Paon'],
    ['Peg', 'Pégase'],
    ['Per', 'Persée'],
    ['Phe', 'Phénix'],
    ['Pic', 'Peintre'],
    ['PsA', 'Poisson Austral'],
    ['Psc', 'Poissons'],
    ['Pup', 'Poupe'],
    ['Pyx', 'Boussole'],
    ['Ret', 'Réticule'],
    ['Scl', 'Sculpteur'],
    ['Sco', 'Scorpion'],
    ['Sct', 'Écu de Sobieski'],
    ['Ser', 'Serpent'],
    ['Sex', 'Sextant'],
    ['Sge', 'Flèche'],
    ['Sgr', 'Sagittaire'],
    ['Tau', 'Taureau'],
    ['Tel', 'Télescope'],
    ['TrA', 'Triangle Austral'],
    ['Tri', 'Triangle'],
    ['Tuc', 'Toucan'],
    ['UMa', 'Grande Ourse'],
    ['UMi', 'Petite Ourse'],
    ['Vel', 'Voiles'],
    ['Vir', 'Vierge'],
    ['Vol', 'Poisson Volant'],
    ['Vul', 'Petit Renard']
];